# Site
title: LiloKids
subtitle: Uso criativo de tecnologia

# URL
url: http://lilokids.lilo.zone
baseurl: /
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4449
future: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
